### ISSUE TITLE
SQLi 판별 모듈 개발

### ISSUE THREAD

**Issue by icaros7** [icaros7/sqli-detector-p2#2]
# SQLi 판별 모듈 `sqli.py` 개발 정책

---
## TODO: 
- [ ] GET/POST 메소드 별 대응
- [ ] POST 파라미터 구분
- [ ] `sqlmap` 비동기 출력
